baseURL: "https://kir-gadjello.github.io/"
title: Kirill Gadjello's personal blog and website
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Hopefully Generally Useful?
  description: "Kirill Gadjello's personal blog and website"
  keywords: [Blog, Portfolio, PaperMod]
  author: kir-gadjello
  author: ["Kirill Gadjello"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  mainSections:
  - posts

  assets:
    disableHLJS: true # to disable highlight.js
    disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Home"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: kir-gadjello-weblog
    subtitle: "This is subtitle"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Greetings, stranger  💠\U0001F44B"
    Content: Welcome to my blog where I hope to gather generally useful information

  socialIcons:
    - name: github
      url: "https://github.com/kir-gadjello"
    - name: email
      url: "mailto:kirill.gadjello@protonmail.com"
    - name: telegram
      url: "https://t.me/reactiveloop"

  analytics:
    google:
      SiteVerificationTag: ""
    bing:
      SiteVerificationTag: ""
    yandex:
      SiteVerificationTag: ""

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # editPost:
  #   URL: "https://github.com/kir-gadjello/blog"
  #   Text: "Suggest Changes" # edit text
  #   appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    # - identifier: categories
    #   name: categories
    #   url: /categories/
    #   weight: 10
    - identifier: about
      cls: ''
      name: About Me
      url: /about/
      weight: 10
    - identifier: donate
      cls: ''
      name: "Donate"
      url: /donate/
      weight: 20
    - identifier: tags
      cls: ''
      name: Tags
      url: /tags/
      weight: 100
    # - identifier: Home
    #   name: example.org
    #   url: https://example.org
    #   weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: obsidian

